### ISSUE TITLE
SPARQL Label Text Search

### ISSUE THREAD

**Issue by loretoparisi** [cwrc/wikidata-entity-lookup#2]
I have found that for both  the api `getPersonLookupURI` and `findPerson` I get the same uri with the `api.php`:

```
> wikidata.findPerson('jones').then((result)=>{ console.log(result) })
----> https://www.wikidata.org/w/api.php?action=wbsearchentities&search=jones&language=en&limit=5&format=json&uselang=en
```

and

```
> wikidata.getPersonLookupURI('jones')
----> https://www.wikidata.org/w/api.php?action=wbsearchentities&search=jones&language=en&limit=5&format=json&uselang=en
```

while in the docs I should end with a SPARQL query like:

```sparql
SELECT DISTINCT ?s ?label WHERE { \
          SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
          ?s rdfs:label ?label . \
          FILTER (CONTAINS (?label,%s))
        }
        LIMIT %@
```

**Comment by jchartrand** [comment]
Thank you for your comments.  

We don't use a SPARQL endpoint, as explained in this section of the README:

https://github.com/cwrc/wikidata-entity-lookup#why-not-sparql

Which docs (a link to the doc would be best) suggest that you should get a SPARQL query?

Any suggestions for updating our docs would be much appreciated.  Preferably as a pull request.

**Comment by loretoparisi** [comment]
@jchartrand hello, it was actually a comment in this code https://github.com/cwrc/wikidata-entity-lookup/blob/d4f0e2bde621c8f8a6ee0ac82b52fa713aba09ce/src/index.js#L49

**Comment by jchartrand** [comment]
Thank you.  Yes, that's old code that had been commented out.  I've removed the comment and closed this issue.
